### ISSUE TITLE
Resolution bug docked

### ISSUE THREAD

**Issue by lowburger** [CompSciOrBust/Amiigo#15] opened 2022-07-21 06:25 UTC
Hi,

When on docked mode 1080p and open Amiigo homebrew on applet mode, resolution of homebrew become 1280x720 and in bottom left corner of screen instead of fill screen.

Thx

**Comment by CompSciOrBust** [comment] 2022-07-22 05:00
I don't have time to work on Amiigo right now, but I do have a suspicion of what the issue is. Could you tell me if the issue fixes itself if you undock and then redock the Switch while Amiigo is running?

Arriba has code to change the resolution when the dock status changes but I think I may have forgotten to check it when the app is launched so it assumes that it is in handheld mode.

**Comment by lowburger** [comment] 2022-07-24 08:50
> Could you tell me if the issue fixes itself if you undock and then redock the Switch while Amiigo is running?
> 

I did this test and it happens as you said, after redock image is back to 1080p

**Comment by CompSciOrBust** [comment] 2022-07-24 08:52
Thanks. I know how to fix it then, although it might be a couple of weeks until I have time to do so.

**Comment by CompSciOrBust** [comment] 2022-08-14 22:19
I've got this half fixed on my local copy. For some reason in full memory mode homebrew will automatically receive a callback telling it to change resolution, but in applet mode that doesn't happen. I always test in full memory mode to avoid fatals crashing my entire console which is why I'd never countered this before (also because I very rarely use the dock). I'll get a fix out soon.

**Comment by CompSciOrBust** [comment] 2022-08-18 01:33
This is completely fixed in e8b1367ed6eee3592fffef7db2f790031ee3f262 and will probably be released tomorrow.

**Closed as completed by CompSciOrBust** 2022-08-18 01:33 UTC
