### ISSUE TITLE
Wrong Amiibo Smash Ultimate

### ISSUE THREAD

**Issue by SaferLoom** [CompSciOrBust/Amiigo#3] opened 2020-01-02 18:47 UTC
When I try to save progress of my Virtual Amiibo (created on Amiibo Maker), Smash Ultimate show me an error: This is a wrong Amiibo. 
Atmosphere 0.10.1 / Firmware 9.1.0
Sorry for my english.

**Comment by CompSciOrBust** [comment] 2020-01-03 23:03
I think this is either a bug with the Amiibo API or Emuiibo. Could you try creating the Amiibo using Emutool which us provided by xor troll instead? If it doesn't work with this it must be a issue with the Amiibo api since we're both using it for getting Amiibo ids. https://github.com/XorTroll/emuiibo/releases/download/0.4/emutool-v0.4.zip

**Comment by SaferLoom** [comment] 2020-01-03 23:50
I think it is the Amiibo API. When I use Emutool it works correctly. I enclose two images, the first of Emutool's Virtual Amiibos, the second of Amiibo Maker's Virtual Amiibos. The files shown are from the "model.json" files. As you see the Amiibo Maker is blank. (The same happens with the common.json file, the Amiibo Maker file is blank (0 bytes), while the Emutool file has information.) Thanks for the reply.
![15780952553872384865561208658234](https://user-images.githubusercontent.com/59451622/71755658-62f73280-2e6a-11ea-85d1-5a1fc622a557.jpg)
![Uploading 15780953349897656631274239575832.jpg…]()

**Comment by SaferLoom** [comment] 2020-01-03 23:56
Sorry for the mess of images. This is the Amiibo Maker file.
![15780956971025210075382544082045](https://user-images.githubusercontent.com/59451622/71755854-6fc85600-2e6b-11ea-961c-a767dbe23f3b.jpg)

**Comment by CompSciOrBust** [comment] 2020-01-04 00:17
Ah that seems like a issue with Amiigo. My best guess would be that maybe the amiibo api has updated the names of the data it returns. I'll start looking in to it now but I won't be near a pc for a few days so I'm not sure when I'll be able to release a update. If it's a easy fix I'll ask if someone in Atlas can pr the change and upload a fixed build.

Edit: Which Amiibo in particular did you create? Knowing the name will probably help debug the issue further.

Edit 2: I just searched the id you showed in the amiibo api. Is it Charizard? Also is this the only Amiibo you've tried or does the issue happen with every Amiibo?

**Comment by SaferLoom** [comment] 2020-01-04 01:05
Use that Amiibo as an example, but it happens with everyone. All Emutool Amiibos work without problem, and all Amiibo Maker have two blank files.
Clarification: The first image (where an ID is seen) is from an Emutool Virtual Amiibo. The second image is from Amiibo Maker Virtual Amiibo (I can't show it because it's blank, but it should look like the first image, only without any ID).

**Comment by CompSciOrBust** [comment] 2020-01-04 02:54
They seem to be working fine for me. Could you upload the data cached from the amiibo api for me? It should be in /config/amiigo/API.json on your sd card. After you've uploaded it try deleting it from your sd card and deleting the amiibos you made with Amiigo maker, that could fix the issue but I'm not sure.

**Comment by SaferLoom** [comment] 2020-01-04 03:09
Ok in a moment I will do what you mentioned. I want to clarify that Amiibo detects it, but wanting to register it (save progress in Super Smash Ultimate) shows me an error. (Wrong Amiibo).

Edit:
[APIjson.zip](https://github.com/CompSciOrBust/Amiigo/files/4021499/APIjson.zip)


Thx for your time.

Edit 2: I just deleted the file you mentioned to me and the Amiibo created, but the same thing happens to me.

**Comment by SaferLoom** [comment] 2020-01-04 03:18
.

**Comment by CompSciOrBust** [comment] 2020-01-05 17:23
I've tried everything I can think of to reproduce the bug but I can't get it to occur. I'm on the same fw and Atmosphere version as you. Maybe it's something to do with other sysmodules that you're using? Are you running Kosmos or plain Atmosphere? Also are you using a exFat card or Fat32? I'll do everything I can to fix it but I can't identify why it's happening. You're cached Amiibo API data is fine so it's definitely a issue with Amiigo.

**Comment by SaferLoom** [comment] 2020-01-05 18:28
I have an exfat SD. Can you register the Amiibo Maker Virtual Amiibo in Super Smash Bros? In a few moments I send you a video of exactly what happens to me, maybe it helps you with something.

Edit: https://drive.google.com/file/d/1DyKX2oa_Pe4yK65IOLEskBPwoPsj4pI1/view?usp=drivesdk

**Comment by CompSciOrBust** [comment] 2020-01-15 13:43
I think the issue is with Emuiibo. I don't think XorTroll has added support for writing data back to the Virtual Amiibo yet so you can load them in games but you can't save data to them.

**Comment by ghost** [comment] 2020-02-04 16:44
I have the same issue. Tried an inkling amiibo.

1st revision switch (S/N starts with XAJ4, if this helps)

The "Wrong amiibo" message happens as soon as I try to save anything to it. Haven't tried the emuiibo itself, only with amiigo.

**Comment by ghost** [comment] 2020-02-04 16:44
Btw I have Atmosphere and System 9.1.0

**Comment by CompSciOrBust** [comment] 2020-02-04 16:50
Amiigo's Amiibo chooser just sends commands to Emuiibo to change the current Amiibo so until Xor implements saving data to virtual Amiibos I can't do anything to fix this on the Amiigo side. You can open a issue on the Emuiibo repo here. https://github.com/XorTroll/emuiibo/issues

**Comment by CompSciOrBust** [comment] 2021-09-07 01:28
Closing because it's not part of Amiigo and I think Xor has added this to Emuiibo.

**Closed as completed by CompSciOrBust** 2021-09-07 01:28 UTC
Labels: bug
